export default [
    { country: 'hk', countryName: 'Hong Kong', lifeExpectancyMales: 82.84, lifeExpectancyFemales: 88.13 },
    { country: 'jp', countryName: 'Japan', lifeExpectancyMales: 81.69, lifeExpectancyFemales: 87.74 },
    { country: 'kr', countryName: 'South Korea', lifeExpectancyMales: 81.19, lifeExpectancyFemales: 87.16 },
    { country: 'pf', countryName: 'French Polynesia', lifeExpectancyMales: 81.78, lifeExpectancyFemales: 86.5 },
    { country: 'ad', countryName: 'Andorra', lifeExpectancyMales: 82.1, lifeExpectancyFemales: 86.11 },
    { country: 'ch', countryName: 'Switzerland', lifeExpectancyMales: 82.01, lifeExpectancyFemales: 85.83 },
    { country: 'au', countryName: 'Australia', lifeExpectancyMales: 82.1, lifeExpectancyFemales: 85.74 },
    { country: 'sg', countryName: 'Singapore', lifeExpectancyMales: 81.24, lifeExpectancyFemales: 86.24 },
    { country: 'it', countryName: 'Italy', lifeExpectancyMales: 81.57, lifeExpectancyFemales: 85.75 },
    { country: 'es', countryName: 'Spain', lifeExpectancyMales: 80.96, lifeExpectancyFemales: 86.31 },
    { country: 're', countryName: 'Réunion', lifeExpectancyMales: 80.53, lifeExpectancyFemales: 86.33 },
    { country: 'fr', countryName: 'France', lifeExpectancyMales: 80.43, lifeExpectancyFemales: 86.09 },
    { country: 'no', countryName: 'Norway', lifeExpectancyMales: 81.75, lifeExpectancyFemales: 84.85 },
    { country: 'mt', countryName: 'Malta', lifeExpectancyMales: 81.27, lifeExpectancyFemales: 85.26 },
    { country: 'gg', countryName: 'Guernsey', lifeExpectancyMales: 81.01, lifeExpectancyFemales: 85.58 },
    { country: 'se', countryName: 'Sweden', lifeExpectancyMales: 81.44, lifeExpectancyFemales: 85.1 },
    { country: 'mo', countryName: 'Macao', lifeExpectancyMales: 80.83, lifeExpectancyFemales: 85.25 },
    { country: 'ae', countryName: 'United Arab Emirates', lifeExpectancyMales: 81.98, lifeExpectancyFemales: 84.2 },
    { country: 'is', countryName: 'Iceland', lifeExpectancyMales: 80.98, lifeExpectancyFemales: 84.51 },
    { country: 'ca', countryName: 'Canada', lifeExpectancyMales: 80.43, lifeExpectancyFemales: 84.83 },
    { country: 'mq', countryName: 'Martinique', lifeExpectancyMales: 79.25, lifeExpectancyFemales: 85.62 },
    { country: 'il', countryName: 'Israel', lifeExpectancyMales: 80.18, lifeExpectancyFemales: 84.59 },
    { country: 'ie', countryName: 'Ireland', lifeExpectancyMales: 80.37, lifeExpectancyFemales: 84.48 },
    { country: 'qa', countryName: 'Qatar', lifeExpectancyMales: 81.61, lifeExpectancyFemales: 83.37 },
    { country: 'pt', countryName: 'Portugal', lifeExpectancyMales: 79.44, lifeExpectancyFemales: 85.12 },
    { country: 'bm', countryName: 'Bermuda', lifeExpectancyMales: 78.86, lifeExpectancyFemales: 85.74 },
    { country: 'lu', countryName: 'Luxembourg', lifeExpectancyMales: 80.57, lifeExpectancyFemales: 83.84 },
    { country: 'nl', countryName: 'Netherlands', lifeExpectancyMales: 80.54, lifeExpectancyFemales: 83.74 },
    { country: 'be', countryName: 'Belgium', lifeExpectancyMales: 79.86, lifeExpectancyFemales: 84.33 },
    { country: 'nz', countryName: 'New Zealand', lifeExpectancyMales: 80.41, lifeExpectancyFemales: 83.77 },
    { country: 'gp', countryName: 'Guadeloupe', lifeExpectancyMales: 78.13, lifeExpectancyFemales: 85.53 },
    { country: 'at', countryName: 'Austria', lifeExpectancyMales: 79.54, lifeExpectancyFemales: 84.32 },
    { country: 'dk', countryName: 'Denmark', lifeExpectancyMales: 80.02, lifeExpectancyFemales: 83.86 },
    { country: 'fi', countryName: 'Finland', lifeExpectancyMales: 79.17, lifeExpectancyFemales: 84.67 },
    { country: 'gr', countryName: 'Greece', lifeExpectancyMales: 79.29, lifeExpectancyFemales: 84.33 },
    { country: 'pr', countryName: 'Puerto Rico', lifeExpectancyMales: 78.03, lifeExpectancyFemales: 85.24 },
    { country: 'cy', countryName: 'Cyprus', lifeExpectancyMales: 79.64, lifeExpectancyFemales: 83.67 },
    { country: 'si', countryName: 'Slovenia', lifeExpectancyMales: 78.9, lifeExpectancyFemales: 84.34 },
    { country: 'de', countryName: 'Germany', lifeExpectancyMales: 79.02, lifeExpectancyFemales: 83.76 },
    { country: 'gb', countryName: 'United Kingdom', lifeExpectancyMales: 79.36, lifeExpectancyFemales: 83.21 },
    { country: 'bh', countryName: 'Bahrain', lifeExpectancyMales: 80.67, lifeExpectancyFemales: 81.99 },
    { country: 'cl', countryName: 'Chile', lifeExpectancyMales: 79.24, lifeExpectancyFemales: 83.08 },
    { country: 'mv', countryName: 'Maldives', lifeExpectancyMales: 79.69, lifeExpectancyFemales: 82.82 },
    { country: 'im', countryName: 'Isle of Man', lifeExpectancyMales: 78.93, lifeExpectancyFemales: 83.13 },
    { country: 'cr', countryName: 'Costa Rica', lifeExpectancyMales: 78.13, lifeExpectancyFemales: 83.42 },
    { country: 'tw', countryName: 'Taiwan', lifeExpectancyMales: 77.63, lifeExpectancyFemales: 83.61 },
    { country: 'kw', countryName: 'Kuwait', lifeExpectancyMales: 79.25, lifeExpectancyFemales: 81.85 },
    { country: 'ky', countryName: 'Cayman Islands', lifeExpectancyMales: 77.98, lifeExpectancyFemales: 82.87 },
    { country: 'fo', countryName: 'Faroe Islands', lifeExpectancyMales: 78.17, lifeExpectancyFemales: 82.5 },
    { country: 'om', countryName: 'Oman', lifeExpectancyMales: 78.49, lifeExpectancyFemales: 81.88 },
    { country: 'cz', countryName: 'Czechia', lifeExpectancyMales: 77.0, lifeExpectancyFemales: 82.64 },
    { country: 'je', countryName: 'Jersey', lifeExpectancyMales: 77.72, lifeExpectancyFemales: 81.76 },
    { country: 'al', countryName: 'Albania', lifeExpectancyMales: 77.73, lifeExpectancyFemales: 81.45 },
    { country: 'pa', countryName: 'Panama', lifeExpectancyMales: 76.65, lifeExpectancyFemales: 82.56 },
    { country: 'us', countryName: 'United States', lifeExpectancyMales: 76.86, lifeExpectancyFemales: 81.85 },
    { country: 'ee', countryName: 'Estonia', lifeExpectancyMales: 74.9, lifeExpectancyFemales: 83.04 },
    { country: 'nc', countryName: 'New Caledonia', lifeExpectancyMales: 76.28, lifeExpectancyFemales: 81.29 },
    { country: 'sa', countryName: 'Saudi Arabia', lifeExpectancyMales: 77.1, lifeExpectancyFemales: 81.16 },
    { country: 'pl', countryName: 'Poland', lifeExpectancyMales: 74.88, lifeExpectancyFemales: 82.35 },
    { country: 'hr', countryName: 'Croatia', lifeExpectancyMales: 75.41, lifeExpectancyFemales: 81.69 },
    { country: 'sk', countryName: 'Slovakia', lifeExpectancyMales: 75.02, lifeExpectancyFemales: 81.58 },
    { country: 'uy', countryName: 'Uruguay', lifeExpectancyMales: 74.19, lifeExpectancyFemales: 81.92 },
    { country: 'cu', countryName: 'Cuba', lifeExpectancyMales: 75.67, lifeExpectancyFemales: 80.52 },
    { country: 'xk', countryName: 'Kosovo', lifeExpectancyMales: 75.8, lifeExpectancyFemales: 80.12 },
    { country: 'cn', countryName: 'China', lifeExpectancyMales: 75.2, lifeExpectancyFemales: 80.93 },
    { country: 'ba', countryName: 'Bosnia and Herzegovina', lifeExpectancyMales: 74.42, lifeExpectancyFemales: 80.9 },
    { country: 'lb', countryName: 'Lebanon', lifeExpectancyMales: 75.74, lifeExpectancyFemales: 79.73 },
    { country: 'jo', countryName: 'Jordan', lifeExpectancyMales: 75.71, lifeExpectancyFemales: 80.19 },
    { country: 'pe', countryName: 'Peru', lifeExpectancyMales: 75.41, lifeExpectancyFemales: 80.12 },
    { country: 'co', countryName: 'Colombia', lifeExpectancyMales: 74.95, lifeExpectancyFemales: 80.45 },
    { country: 'ir', countryName: 'Iran', lifeExpectancyMales: 75.79, lifeExpectancyFemales: 79.63 },
    { country: 'ag', countryName: 'Antigua and Barbuda', lifeExpectancyMales: 74.55, lifeExpectancyFemales: 80.29 },
    { country: 'lk', countryName: 'Sri Lanka', lifeExpectancyMales: 74.24, lifeExpectancyFemales: 80.59 },
    { country: 'ar', countryName: 'Argentina', lifeExpectancyMales: 74.81, lifeExpectancyFemales: 79.88 },
    { country: 'mk', countryName: 'North Macedonia', lifeExpectancyMales: 75.11, lifeExpectancyFemales: 79.57 },
    { country: 'ec', countryName: 'Ecuador', lifeExpectancyMales: 74.66, lifeExpectancyFemales: 80.14 },
    { country: 'gu', countryName: 'Guam', lifeExpectancyMales: 73.44, lifeExpectancyFemales: 81.42 },
    { country: 'tr', countryName: 'Türkiye', lifeExpectancyMales: 74.53, lifeExpectancyFemales: 79.86 },
    { country: 'me', countryName: 'Montenegro', lifeExpectancyMales: 73.73, lifeExpectancyFemales: 80.31 },
    { country: 'hu', countryName: 'Hungary', lifeExpectancyMales: 73.71, lifeExpectancyFemales: 80.19 },
    { country: 'gf', countryName: 'French Guiana', lifeExpectancyMales: 74.13, lifeExpectancyFemales: 79.99 },
    { country: 'cw', countryName: 'Curaçao', lifeExpectancyMales: 72.46, lifeExpectancyFemales: 80.82 },
    { country: 'rs', countryName: 'Serbia', lifeExpectancyMales: 73.5, lifeExpectancyFemales: 80.04 },
    { country: 'my', countryName: 'Malaysia', lifeExpectancyMales: 74.27, lifeExpectancyFemales: 79.37 },
    { country: 'tn', countryName: 'Tunisia', lifeExpectancyMales: 73.92, lifeExpectancyFemales: 79.15 },
    { country: 'th', countryName: 'Thailand', lifeExpectancyMales: 72.16, lifeExpectancyFemales: 80.86 },
    { country: 'aw', countryName: 'Aruba', lifeExpectancyMales: 73.7, lifeExpectancyFemales: 78.78 },
    { country: 'dz', countryName: 'Algeria', lifeExpectancyMales: 74.89, lifeExpectancyFemales: 77.7 },
    { country: 'lv', countryName: 'Latvia', lifeExpectancyMales: 71.56, lifeExpectancyFemales: 80.47 },
    { country: 'bb', countryName: 'Barbados', lifeExpectancyMales: 73.63, lifeExpectancyFemales: 78.61 },
    { country: 'cv', countryName: 'Cabo Verde', lifeExpectancyMales: 72.86, lifeExpectancyFemales: 79.21 },
    { country: 'yt', countryName: 'Mayotte', lifeExpectancyMales: 74.09, lifeExpectancyFemales: 78.33 },
    { country: 'lt', countryName: 'Lithuania', lifeExpectancyMales: 71.22, lifeExpectancyFemales: 80.67 },
    { country: 'ro', countryName: 'Romania', lifeExpectancyMales: 72.4, lifeExpectancyFemales: 79.56 },
    { country: 'br', countryName: 'Brazil', lifeExpectancyMales: 72.76, lifeExpectancyFemales: 78.98 },
    { country: 'am', countryName: 'Armenia', lifeExpectancyMales: 71.39, lifeExpectancyFemales: 79.45 },
    { country: 'bg', countryName: 'Bulgaria', lifeExpectancyMales: 72.16, lifeExpectancyFemales: 79.21 },
    { country: 'vi', countryName: 'U.S. Virgin Islands', lifeExpectancyMales: 70.51, lifeExpectancyFemales: 81.35 },
    { country: 'bn', countryName: 'Brunei', lifeExpectancyMales: 73.33, lifeExpectancyFemales: 77.56 },
    { country: 'ma', countryName: 'Morocco', lifeExpectancyMales: 73.17, lifeExpectancyFemales: 77.6 },
    { country: 'gd', countryName: 'Grenada', lifeExpectancyMales: 72.36, lifeExpectancyFemales: 78.36 },
    { country: 'mx', countryName: 'Mexico', lifeExpectancyMales: 72.24, lifeExpectancyFemales: 77.81 },
    { country: 'ni', countryName: 'Nicaragua', lifeExpectancyMales: 72.31, lifeExpectancyFemales: 77.42 },
    { country: 'mu', countryName: 'Mauritius', lifeExpectancyMales: 71.94, lifeExpectancyFemales: 78.18 },
    { country: 'bd', countryName: 'Bangladesh', lifeExpectancyMales: 73.03, lifeExpectancyFemales: 76.37 },
    { country: 'vn', countryName: 'Vietnam', lifeExpectancyMales: 69.88, lifeExpectancyFemales: 79.26 },
    { country: 'bs', countryName: 'Bahamas', lifeExpectancyMales: 70.91, lifeExpectancyFemales: 78.19 },
    { country: 'ge', countryName: 'Georgia', lifeExpectancyMales: 69.57, lifeExpectancyFemales: 79.11 },
    { country: 'by', countryName: 'Belarus', lifeExpectancyMales: 69.53, lifeExpectancyFemales: 79.06 },
    { country: 'az', countryName: 'Azerbaijan', lifeExpectancyMales: 71.56, lifeExpectancyFemales: 77.13 },
    { country: 'kz', countryName: 'Kazakhstan', lifeExpectancyMales: 70.11, lifeExpectancyFemales: 78.39 },
    { country: 'py', countryName: 'Paraguay', lifeExpectancyMales: 70.89, lifeExpectancyFemales: 76.95 },
    { country: 'do', countryName: 'Dominican Republic', lifeExpectancyMales: 70.53, lifeExpectancyFemales: 76.97 },
    { country: 'kp', countryName: 'North Korea', lifeExpectancyMales: 71.46, lifeExpectancyFemales: 75.74 },
    { country: 'sr', countryName: 'Suriname', lifeExpectancyMales: 70.46, lifeExpectancyFemales: 76.83 },
    { country: 'bz', countryName: 'Belize', lifeExpectancyMales: 70.93, lifeExpectancyFemales: 76.5 },
    { country: 'tt', countryName: 'Trinidad and Tobago', lifeExpectancyMales: 70.38, lifeExpectancyFemales: 76.68 },
    { country: 'ua', countryName: 'Ukraine', lifeExpectancyMales: 66.9, lifeExpectancyFemales: 80.2 },
    { country: 'ru', countryName: 'Russia', lifeExpectancyMales: 67.26, lifeExpectancyFemales: 79.04 },
    { country: 'bt', countryName: 'Bhutan', lifeExpectancyMales: 71.31, lifeExpectancyFemales: 74.97 },
    { country: 'to', countryName: 'Tonga', lifeExpectancyMales: 69.37, lifeExpectancyFemales: 76.41 },
    { country: 'hn', countryName: 'Honduras', lifeExpectancyMales: 70.35, lifeExpectancyFemales: 75.5 },
    { country: 'sc', countryName: 'Seychelles', lifeExpectancyMales: 69.94, lifeExpectancyFemales: 76.52 },
    { country: 'lc', countryName: 'Saint Lucia', lifeExpectancyMales: 69.31, lifeExpectancyFemales: 76.3 },
    { country: 'gt', countryName: 'Guatemala', lifeExpectancyMales: 70.31, lifeExpectancyFemales: 74.88 },
    { country: 've', countryName: 'Venezuela', lifeExpectancyMales: 68.72, lifeExpectancyFemales: 76.5 },
    { country: 'uz', countryName: 'Uzbekistan', lifeExpectancyMales: 69.45, lifeExpectancyFemales: 75.4 },
    { country: 'iq', countryName: 'Iraq', lifeExpectancyMales: 70.43, lifeExpectancyFemales: 74.06 },
    { country: 'sy', countryName: 'Syria', lifeExpectancyMales: 69.83, lifeExpectancyFemales: 74.41 },
    { country: 'sv', countryName: 'El Salvador', lifeExpectancyMales: 67.52, lifeExpectancyFemales: 76.26 },
    { country: 'in', countryName: 'India', lifeExpectancyMales: 70.52, lifeExpectancyFemales: 73.6 },
    { country: 'tj', countryName: 'Tajikistan', lifeExpectancyMales: 69.57, lifeExpectancyFemales: 73.98 },
    { country: 'mn', countryName: 'Mongolia', lifeExpectancyMales: 67.24, lifeExpectancyFemales: 76.43 },
    { country: 'ws', countryName: 'Samoa', lifeExpectancyMales: 69.86, lifeExpectancyFemales: 73.66 },
    { country: 'kg', countryName: 'Kyrgyzstan', lifeExpectancyMales: 68.18, lifeExpectancyFemales: 75.25 },
    { country: 'eg', countryName: 'Egypt', lifeExpectancyMales: 69.49, lifeExpectancyFemales: 73.81 },
    { country: 'jm', countryName: 'Jamaica', lifeExpectancyMales: 68.97, lifeExpectancyFemales: 73.99 },
    { country: 'vu', countryName: 'Vanuatu', lifeExpectancyMales: 69.44, lifeExpectancyFemales: 73.93 },
    { country: 'eh', countryName: 'Western Sahara', lifeExpectancyMales: 69.69, lifeExpectancyFemales: 73.55 },
    { country: 'vc', countryName: 'Saint Vincent and the Grenadines', lifeExpectancyMales: 68.66, lifeExpectancyFemales: 74.31 },
    { country: 'md', countryName: 'Moldova', lifeExpectancyMales: 66.57, lifeExpectancyFemales: 75.53 },
    { country: 'id', countryName: 'Indonesia', lifeExpectancyMales: 69.04, lifeExpectancyFemales: 73.27 },
    { country: 'dm', countryName: 'Dominica', lifeExpectancyMales: 68.21, lifeExpectancyFemales: 74.55 },
    { country: 'kh', countryName: 'Cambodia', lifeExpectancyMales: 68.01, lifeExpectancyFemales: 73.19 },
    { country: 'sb', countryName: 'Solomon Islands', lifeExpectancyMales: 69.22, lifeExpectancyFemales: 71.98 },
    { country: 'np', countryName: 'Nepal', lifeExpectancyMales: 68.83, lifeExpectancyFemales: 71.84 },
    { country: 'gy', countryName: 'Guyana', lifeExpectancyMales: 66.51, lifeExpectancyFemales: 73.94 },
    { country: 'tm', countryName: 'Turkmenistan', lifeExpectancyMales: 66.87, lifeExpectancyFemales: 72.84 },
    { country: 'gl', countryName: 'Greenland', lifeExpectancyMales: 68.09, lifeExpectancyFemales: 72.44 },
    { country: 'ph', countryName: 'Philippines', lifeExpectancyMales: 66.89, lifeExpectancyFemales: 72.82 },
    { country: 'st', countryName: 'Sao Tome and Principe', lifeExpectancyMales: 66.24, lifeExpectancyFemales: 73.73 },
    { country: 'ly', countryName: 'Libya', lifeExpectancyMales: 68.27, lifeExpectancyFemales: 70.42 },
    { country: 'ye', countryName: 'Yemen', lifeExpectancyMales: 67.23, lifeExpectancyFemales: 71.39 },
    { country: 'bw', countryName: 'Botswana', lifeExpectancyMales: 66.67, lifeExpectancyFemales: 71.7 },
    { country: 'la', countryName: 'Laos', lifeExpectancyMales: 66.78, lifeExpectancyFemales: 71.25 },
    { country: 'sn', countryName: 'Senegal', lifeExpectancyMales: 66.79, lifeExpectancyFemales: 70.75 },
    { country: 'er', countryName: 'Eritrea', lifeExpectancyMales: 66.51, lifeExpectancyFemales: 70.66 },
    { country: 'bo', countryName: 'Bolivia', lifeExpectancyMales: 66.13, lifeExpectancyFemales: 71.14 },
    { country: 'mr', countryName: 'Mauritania', lifeExpectancyMales: 66.5, lifeExpectancyFemales: 70.48 },
    { country: 'ga', countryName: 'Gabon', lifeExpectancyMales: 65.91, lifeExpectancyFemales: 71.05 },
    { country: 'ug', countryName: 'Uganda', lifeExpectancyMales: 65.27, lifeExpectancyFemales: 71.12 },
    { country: 'rw', countryName: 'Rwanda', lifeExpectancyMales: 65.49, lifeExpectancyFemales: 69.89 },
    { country: 'tl', countryName: 'Timor-Leste', lifeExpectancyMales: 66.07, lifeExpectancyFemales: 69.44 },
    { country: 'pk', countryName: 'Pakistan', lifeExpectancyMales: 65.33, lifeExpectancyFemales: 70.16 },
    { country: 'na', countryName: 'Namibia', lifeExpectancyMales: 63.33, lifeExpectancyFemales: 71.34 },
    { country: 'mw', countryName: 'Malawi', lifeExpectancyMales: 64.07, lifeExpectancyFemales: 70.56 },
    { country: 'fj', countryName: 'Fiji', lifeExpectancyMales: 65.34, lifeExpectancyFemales: 69.36 },
    { country: 'et', countryName: 'Ethiopia', lifeExpectancyMales: 64.08, lifeExpectancyFemales: 70.73 },
    { country: 'fm', countryName: 'Micronesia', lifeExpectancyMales: 63.49, lifeExpectancyFemales: 71.12 },
    { country: 'tz', countryName: 'Tanzania', lifeExpectancyMales: 64.2, lifeExpectancyFemales: 69.78 },
    { country: 'mm', countryName: 'Myanmar', lifeExpectancyMales: 63.79, lifeExpectancyFemales: 70.16 },
    { country: 'km', countryName: 'Comoros', lifeExpectancyMales: 64.79, lifeExpectancyFemales: 68.93 },
    { country: 'ki', countryName: 'Kiribati', lifeExpectancyMales: 64.58, lifeExpectancyFemales: 68.17 },
    { country: 'zm', countryName: 'Zambia', lifeExpectancyMales: 63.94, lifeExpectancyFemales: 68.67 },
    { country: 'sd', countryName: 'Sudan', lifeExpectancyMales: 63.27, lifeExpectancyFemales: 69.63 },
    { country: 'za', countryName: 'South Africa', lifeExpectancyMales: 62.61, lifeExpectancyFemales: 69.6 },
    { country: 'pg', countryName: 'Papua New Guinea', lifeExpectancyMales: 63.74, lifeExpectancyFemales: 69.08 },
    { country: 'af', countryName: 'Afghanistan', lifeExpectancyMales: 64.47, lifeExpectancyFemales: 67.54 },
    { country: 'dj', countryName: 'Djibouti', lifeExpectancyMales: 63.52, lifeExpectancyFemales: 68.51 },
    { country: 'gm', countryName: 'Gambia', lifeExpectancyMales: 64.17, lifeExpectancyFemales: 67.53 },
    { country: 'cg', countryName: 'Congo', lifeExpectancyMales: 64.12, lifeExpectancyFemales: 67.46 },
    { country: 'gh', countryName: 'Ghana', lifeExpectancyMales: 63.13, lifeExpectancyFemales: 67.94 },
    { country: 'ps', countryName: 'Palestine', lifeExpectancyMales: 59.69, lifeExpectancyFemales: 71.5 },
    { country: 'ht', countryName: 'Haiti', lifeExpectancyMales: 61.73, lifeExpectancyFemales: 68.3 },
    { country: 'ao', countryName: 'Angola', lifeExpectancyMales: 62.1, lifeExpectancyFemales: 67.14 },
    { country: 'sz', countryName: 'Eswatini', lifeExpectancyMales: 61.19, lifeExpectancyFemales: 66.95 },
    { country: 'gw', countryName: 'Guinea-Bissau', lifeExpectancyMales: 61.66, lifeExpectancyFemales: 66.36 },
    { country: 'gq', countryName: 'Equatorial Guinea', lifeExpectancyMales: 62.04, lifeExpectancyFemales: 65.66 },
    { country: 'cm', countryName: 'Cameroon', lifeExpectancyMales: 61.52, lifeExpectancyFemales: 65.94 },
    { country: 'bi', countryName: 'Burundi', lifeExpectancyMales: 61.6, lifeExpectancyFemales: 65.7 },
    { country: 'ke', countryName: 'Kenya', lifeExpectancyMales: 61.46, lifeExpectancyFemales: 65.92 },
    { country: 'mg', countryName: 'Madagascar', lifeExpectancyMales: 61.94, lifeExpectancyFemales: 65.38 },
    { country: 'mz', countryName: 'Mozambique', lifeExpectancyMales: 60.3, lifeExpectancyFemales: 66.54 },
    { country: 'zw', countryName: 'Zimbabwe', lifeExpectancyMales: 60.23, lifeExpectancyFemales: 65.01 },
    { country: 'tg', countryName: 'Togo', lifeExpectancyMales: 62.54, lifeExpectancyFemales: 62.92 },
    { country: 'lr', countryName: 'Liberia', lifeExpectancyMales: 60.88, lifeExpectancyFemales: 63.44 },
    { country: 'ci', countryName: 'Côte d\'Ivoire', lifeExpectancyMales: 60.02, lifeExpectancyFemales: 64.13 },
    { country: 'cd', countryName: 'DR Congo', lifeExpectancyMales: 59.79, lifeExpectancyFemales: 64.04 },
    { country: 'sl', countryName: 'Sierra Leone', lifeExpectancyMales: 60.06, lifeExpectancyFemales: 63.5 },
    { country: 'ne', countryName: 'Niger', lifeExpectancyMales: 60.26, lifeExpectancyFemales: 62.13 },
    { country: 'bf', countryName: 'Burkina Faso', lifeExpectancyMales: 58.92, lifeExpectancyFemales: 63.22 },
    { country: 'bj', countryName: 'Benin', lifeExpectancyMales: 59.35, lifeExpectancyFemales: 62.21 },
    { country: 'gn', countryName: 'Guinea', lifeExpectancyMales: 59.52, lifeExpectancyFemales: 61.9 },
    { country: 'ml', countryName: 'Mali', lifeExpectancyMales: 59.04, lifeExpectancyFemales: 61.9 },
    { country: 'so', countryName: 'Somalia', lifeExpectancyMales: 56.35, lifeExpectancyFemales: 61.39 },
    { country: 'ss', countryName: 'South Sudan', lifeExpectancyMales: 54.64, lifeExpectancyFemales: 60.63 },
    { country: 'cf', countryName: 'Central African Republic', lifeExpectancyMales: 55.26, lifeExpectancyFemales: 59.29 },
    { country: 'ls', countryName: 'Lesotho', lifeExpectancyMales: 54.62, lifeExpectancyFemales: 60.01 },
    { country: 'td', countryName: 'Chad', lifeExpectancyMales: 53.2, lifeExpectancyFemales: 57.01 },
    { country: 'ng', countryName: 'Nigeria', lifeExpectancyMales: 54.18, lifeExpectancyFemales: 54.74 }
];
