import type {Vip} from "~/interfaces/Vip.ts";

const vipData: Vip[] = [
    {
        name: 'Donald Trump',
        source: 'President, dictator, pedophile, colossal piece of shit',
        squareImage: 'https://imageio.forbes.com/specials-images/imageserve/5638e53de4b0ffa7afe6a26a/0x0.jpg?format=jpg&crop=704,704,x27,y32,safe&fit=bounds',
        dob: '1946-06-14',
        country: 'USA',
        countryCode: 'us',
        isMale: true
    },
    {
        name: 'Elon Musk',
        source: 'Self-made failure, will die alone with no friends',
        squareImage: 'https://imageio.forbes.com/specials-images/imageserve/62d700cd6094d2c180f269b9/0x0.jpg?format=jpg&crop=959,959,x0,y0,safe&fit=bounds',
        dob: '1971-06-28',
        country: 'USA (born South African)',
        countryCode: 'us',
        isMale: true
    },
    {
        name: 'Mark Zuckerberg',
        source: 'Billionaire, lizard, moron',
        squareImage: 'https://specials-images.forbesimg.com/imageserve/5c76b7d331358e35dd2773a9/416x416.jpg?background=000000&cropX1=0&cropX2=4401&cropY1=0&cropY2=4401',
        dob: '1984-05-14',
        country: 'USA',
        countryCode: 'us',
        isMale: true
    },
    {
        name: 'Jeff Bezos',
        source: 'Billionaire, taste-lacking imbecile',
        squareImage: 'https://imageio.forbes.com/specials-images/imageserve/67531eb2b5f7c9e191f632d7/0x0.jpg?format=jpg&crop=711,713,x316,y125,safe&fit=bounds',
        dob: '1964-01-12',
        country: 'USA',
        countryCode: 'us',
        isMale: true
    },
    {
        name: 'Peter Thiel',
        source: 'Billionaire, self-proclaimed antechrist',
        squareImage: 'https://specials-images.forbesimg.com/imageserve/5a836fff31358e4955ad6549/416x416.jpg?background=000000&cropX1=234&cropX2=790&cropY1=7&cropY2=563',
        dob: '1967-10-11',
        country: 'USA (born West German)',
        countryCode: 'us',
        isMale: true
    },
    {
        name: 'Pierre-Édouard Stérin',
        source: 'Billionaire, far right activist, christian extremist',
        squareImage: 'https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Flessentieldeleco.fr%2Fwp-content%2Fuploads%2F2024%2F07%2Fdfvvdf.jpg&f=1&nofb=1&ipt=95a4041a0f23554f4b07d4990d78693ae2bc428f378c0ca867e507a4b4bacc6b',
        dob: '1974-01-03',
        country: 'France',
        countryCode: 'fr',
        isMale: true
    },
    {
        name: 'J. K. Rowling',
        source: 'Billionaire, unrelenting transphobic old hag',
        squareImage: 'https://specials-images.forbesimg.com/imageserve/5ed56d114231c70006c8f37b/416x416.jpg?background=000000&cropX1=0&cropX2=654&cropY1=96&cropY2=750',
        dob: '1965-07-31',
        country: 'United Kingdom',
        countryCode: 'gb',
        isMale: false
    },
    {
        name: 'Benjamin Netanyahu',
        source: 'Genocidal maniac, dictator, zionist turd',
        squareImage: 'https://thumb.wikimedia.org/wikipedia/commons/thumb/7/74/Benjamin_Netanyahu%2C_February_2023.jpg/500px-Benjamin_Netanyahu%2C_February_2023.jpg',
        dob: '1949-10-21',
        country: 'Israel',
        countryCode: 'il',
        isMale: true
    },
    {
        name: 'Sam Altman',
        source: 'Billionaire, his personality was generated by AI',
        squareImage: 'https://imageio.forbes.com/specials-images/imageserve/661ff92a5f8d9bc634de57c6/0x0.jpg?format=jpg&crop=1619,1620,x601,y68,safe&fit=bounds',
        dob: '1985-04-22',
        country: 'USA',
        countryCode: 'us',
        isMale: true
    },
    {
        name: 'Vladimir Putin',
        source: 'President, dictator, Vlad the Invader',
        squareImage: 'https://thumb.wikimedia.org/wikipedia/commons/thumb/5/57/%D0%92%D0%BB%D0%B0%D0%B4%D0%B8%D0%BC%D0%B8%D1%80_%D0%9F%D1%83%D1%82%D0%B8%D0%BD_%2808-03-2024%29_%28cropped%29_%28higher_res%29.jpg/500px-%D0%92%D0%BB%D0%B0%D0%B4%D0%B8%D0%BC%D0%B8%D1%80_%D0%9F%D1%83%D1%82%D0%B8%D0%BD_%2808-03-2024%29_%28cropped%29_%28higher_res%29.jpg',
        dob: '1952-10-07',
        country: 'Russia',
        countryCode: 'ru',
        isMale: true
    },
    {
        name: 'Stephen Miller',
        source: 'Nazi, Goebbels wannabe, White House official',
        squareImage: 'https://thumb.wikimedia.org/wikipedia/commons/thumb/7/7d/Stephen_Miller_July_2025.jpg/500px-Stephen_Miller_July_2025.jpg',
        dob: '1985-08-23',
        country: 'USA',
        countryCode: 'us',
        isMale: true
    },
    {
        name: 'Nigel Farage',
        source: 'British politician, racist moron',
        squareImage: 'https://thumb.wikimedia.org/wikipedia/commons/thumb/d/d7/Official_portrait_of_Nigel_Farage_MP_crop_2.jpg/500px-Official_portrait_of_Nigel_Farage_MP_crop_2.jpg',
        dob: '1964-04-03',
        country: 'United Kingdom',
        countryCode: 'gb',
        isMale: true
    },
    {
        name: 'Marine Le Pen',
        source: 'Convicted politician, racist and daughter of a fascist',
        squareImage: 'https://thumb.wikimedia.org/wikipedia/commons/thumb/8/81/Marine_Le_Pen_2025_%28cropped%29.jpg/500px-Marine_Le_Pen_2025_%28cropped%29.jpg',
        dob: '1968-08-05',
        country: 'France',
        countryCode: 'fr',
        isMale: false
    },
    {
        name: 'Nick Fuentes',
        source: 'Christian nationalist, neonazi, incel',
        squareImage: 'https://upload.wikimedia.org/wikipedia/commons/9/95/Nick_Fuentes_screencap_from_July_2022_virtual_debate.png',
        dob: '1998-08-18',
        country: 'USA',
        countryCode: 'us',
        isMale: true
    },
    {
        name: 'Andrew Tate',
        source: 'Human trafficker, misogynistic douchebag',
        squareImage: 'https://thumb.wikimedia.org/wikipedia/commons/thumb/a/a5/Andrew_Tate_-_James_Tamim_Upload_%28Cropped_Wide_Portrait%29.png/500px-Andrew_Tate_-_James_Tamim_Upload_%28Cropped_Wide_Portrait%29.png',
        dob: '1986-12-01',
        country: 'United Kingdom',
        countryCode: 'gb',
        isMale: true
    },
    {
        name: 'Charlie Kirk',
        source: 'Dead far right influencer',
        squareImage: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ8k7XzV5WAWC2G0QhkHk-wHGlktYUFDBNIIrXXZsUhFBbiTcOgEgmmSmU&s=10',
        dob: '1993-10-14',
        dod: '2025-09-10',
        country: 'USA',
        countryCode: 'us',
        isMale: true
    },
    {
        name: 'Jean-Marie Le Pen',
        source: 'Dead racist war criminal, politician',
        squareImage: 'https://thumb.wikimedia.org/wikipedia/commons/thumb/d/d4/Le_Pen_Jean-Marie_1999_%283x4_cropped%29.jpg/500px-Le_Pen_Jean-Marie_1999_%283x4_cropped%29.jpg',
        dob: '1928-06-20',
        dod: '2025-01-07',
        country: 'France',
        countryCode: 'fr',
        isMale: true
    },
    {
        name: 'Larry Ellison',
        source: 'Billionaire, OG AI bro, mass surveillance advocate',
        squareImage: 'https://imageio.forbes.com/specials-images/imageserve/5e8b62cfc095010007bffea0/0x0.jpg?format=jpg&crop=4529,4532,x0,y652,safe&height=288&width=288&fit=bounds',
        dob: '1944-08-17',
        country: 'USA',
        countryCode: 'us',
        isMale: true
    },
    {
        name: 'Jeffrey Epstein',
        source: 'Pedophile, child trafficker, murderer',
        squareImage: 'https://upload.wikimedia.org/wikipedia/commons/5/59/Jeffrey_Epstein_mug_shot_%28cropped%29.jpg',
        dob: '1953-01-20',
        dod: '2019-08-10',
        country: 'USA',
        countryCode: 'us',
        isMale: true
    },
    {
        name: 'Ghislaine Maxwell',
        source: 'Pedophile, human trafficker, murderer',
        squareImage: 'https://thumb.wikimedia.org/wikipedia/commons/thumb/8/8c/Ghislaine_Maxwell_MDC_mug_shot.webp/500px-Ghislaine_Maxwell_MDC_mug_shot.webp?utm_source=en.wikipedia.org&utm_campaign=parser&utm_content=thumbnail',
        dob: '1961-12-25',
        country: 'UK',
        countryCode: 'gb',
        isMale: false
    },
    {
        name: 'Bernard Arnault',
        source: 'Billionaire, pretentious asshat',
        squareImage: 'https://imageio.forbes.com/specials-images/imageserve/5dc05518ca425400079c659f/0x0.jpg?format=jpg&crop=4000,4003,x0,y1209,safe&height=288&width=288&fit=bounds',
        dob: '1949-03-05',
        country: 'FR',
        countryCode: 'fr',
        isMale: true
    },
    {
        name: 'Vincent Bolloré',
        source: 'Billionaire, media mogul',
        squareImage: 'https://thumb.wikimedia.org/wikipedia/commons/thumb/7/76/Festival_automobile_international_2014_-_Photocall_-_103.jpg/500px-Festival_automobile_international_2014_-_Photocall_-_103.jpg',
        dob: '1952-04-01',
        country: 'FR',
        countryCode: 'fr',
        isMale: true
    },
    {
        name: 'Laura Loomer',
        source: 'Neonazi, MAGA grifter',
        squareImage: 'https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fplasticsurgerydiary.com%2Fwp-content%2Fuploads%2F2025%2F04%2Flaura-loomer-plastic-surgery4.png',
        dob: '1993-05-21',
        country: 'USA',
        countryCode: 'us',
        isMale: false
    },
    {
        name: 'Robert Kraft',
        source: 'Billionaire, zionist, genocide enthusiast',
        squareImage: 'https://thumb.wikimedia.org/wikipedia/commons/thumb/a/a3/RobertKraftPatriots_%28cropped%29.jpg/500px-RobertKraftPatriots_%28cropped%29.jpg',
        dob: '1941-06-05',
        country: 'USA',
        countryCode: 'us',
        isMale: true
    }
];

export default vipData;
